### ISSUE TITLE
What happened to the old output of "inspect"?

### ISSUE THREAD

**Issue by sbrandtb** [ktrueda/parquet-tools#11]
With the latest release (0.2.5), the output of `inspect` changed from the old output to what you also show in your readme now:

```
############ Column(UpdateTime) ############
name: UpdateTime
path: UpdateTime
max_definition_level: 1
max_repetition_level: 0
physical_type: INT64
logical_type: Timestamp(isAdjustedToUTC=true, timeUnit=milliseconds, is_from_converted_type=true, force_set_converted_type=false)
converted_type (legacy): TIMESTAMP_MILLIS
```

became:

```
■■■■■■■■SchemaElement
■■■■■■■■■■■■type = 2
■■■■■■■■■■■■repetition_type = 1
■■■■■■■■■■■■name = UpdateTime
■■■■■■■■■■■■converted_type = 9
```

I found the old output much more useful, also since at least in my output, opposed to the example in the readme, the types are not even translated to their string-representation, but just integers (1, 9, ...)

Is there any way we can switch that back, or make it switchable by option or so?

**Comment by ktrueda** [comment]
Thank you for making issue.

It's  0610bdaa881bafe7873eeeaf0df8da99af49eec7 .
In that time I need to check all metadata that parquet file has. So I decided to use thrift in inspection instead of pyarrow.

But your idea is very important for me.
How about below


`parquet-tools inspect --simple`
```
############ Column(UpdateTime) ############
name: UpdateTime
path: UpdateTime
max_definition_level: 1
max_repetition_level: 0
physical_type: INT64
logical_type: Timestamp(isAdjustedToUTC=true, timeUnit=milliseconds, is_from_converted_type=true, force_set_converted_type=false)
converted_type (legacy): TIMESTAMP_MILLIS
```

`parquet-tools inspect`
```
■■■■■■■■SchemaElement
■■■■■■■■■■■■type = 2
■■■■■■■■■■■■repetition_type = 1
■■■■■■■■■■■■name = UpdateTime
■■■■■■■■■■■■converted_type = 9
```

**Comment by sbrandtb** [comment]
I would have done it maybe the other way around (`--detail` or even `--thrift` or so for the thrift inspection) because I would guess that most users would be more interested in the "simple" output. Or even make it two different subcommands.

But I am fine with either :)

**Comment by ktrueda** [comment]
@sbrandtb 
I liked your idea. I fixed it and already release v.0.2.6. 
Please check it.

**Comment by sbrandtb** [comment]
Tried it, works. Thank you :smile: (https://hub.docker.com/r/fridevbi/parquet-tools-docker)
