### ISSUE TITLE
num_rows negative

### ISSUE THREAD

**Issue by nicolaerosia** [ktrueda/parquet-tools#18]
Hello,

I've created a PARQUET dump from a Vertica database and upon inspect it with parquet-tools, I see that num_rows is negative. Any ideas? I'm not sure if this is a bug from Vertica or not.

```
############ file meta data ############
created_by: parquet-cpp version 1.0.0-v10.1.1 (build Vertica Analytic Database)
num_columns: 3
num_rows: -1803805480
num_row_groups: 1
format_version: 1.0
serialized_size: 329
```

LE:
When I exported the table, Vertica reported that it had exported `2491161816` rows, which is more than 2^31 (not sure what type num_columns is)

**Comment by ktrueda** [comment]
Thank you for making issue.

I checked code making that output.
https://github.com/ktrueda/parquet-tools/blob/3a3a4f991e3b89f12e4d366c1fd9ec333c060a30/parquet_tools/commands/inspect.py#L69
It only show the number from arrow.

And apache arrow.
https://github.com/apache/arrow/blob/b90e7ddfc9a2d18366322868eca1e1d7c562123d/python/pyarrow/_parquet.pxd#L307

It uses int64_t.


I need to see C++ code. It take some time...

**Comment by ktrueda** [comment]
@nicolaerosia 
Could you check if you can reproduce the same problem using arrow directly.

https://arrow.apache.org/docs/python/parquet.html#finer-grained-reading-and-writing
This is the sample code for printing num_rows.

**Comment by nicolaerosia** [comment]
sure, just did - maybe it's the producer (Vertica) who created the parquet file wrong?
```
>>> parquet_file.metadata
<pyarrow._parquet.FileMetaData object at 0x7fcb242df310>
  created_by: parquet-cpp version 1.0.0-v10.1.1 (build Vertica Analytic Database)
  num_columns: 3
  num_rows: -1803805480
  num_row_groups: 1
  format_version: 1.0
  serialized_size: 329
```

```
>>> pyarrow.__version__
'5.0.0'
```

**Comment by ktrueda** [comment]
Could you run 
```
parquet-tools inspect --detail /path/to/parquet
```
You can see metadata using thrift instead of arrow.

If you will see positive number, then arrow is wrong.
Otherwise vertica is wrong.

**Comment by nicolaerosia** [comment]
OK, I forced installed pyarrow=5.0.0 and thrift
```
■■■■num_rows = -1803805480
■■■■row_groups = list
```

I guess the bug is on Vertica side

**Comment by nicolaerosia** [comment]
seems like parquet-tools needs an old pyarrow which fails to compile for me
https://github.com/ktrueda/parquet-tools/blob/master/pyproject.toml#L16

and eventually I end up with parquet-tools 0.2.0

**Comment by ktrueda** [comment]
Thanks for checking.

I didn't know arrow version was updated recently.
I'll update it.

Anyway I closed this issue.

**Comment by nicolaerosia** [comment]
@ktrueda thank you for looking into this, I have reported it on Vertica forum, https://forum.vertica.com/discussion/242382/corrupt-parquet-dump-when-dumping-over-2-31-rows/p1?new=1

**Comment by ktrueda** [comment]
@nicolaerosia 
FYI

I checked parquet format.
https://github.com/apache/parquet-format#metadata

FileMetaData.num_rows is `64 bit signed ints`. 
I believe that 32bit int is used in vertica.

**Comment by nicolaerosia** [comment]
thanks!
